import { mkdir } from 'node:fs/promises';
import { startServer } from './server.js';
import { chromium } from 'playwright';
await mkdir('screenshots/ship', { recursive: true });
const { server, port } = await startServer(0);
const browser = await chromium.launch({ args: ['--no-sandbox', '--enable-unsafe-swiftshader', '--use-angle=swiftshader-webgl'] });
const page = await browser.newPage({ viewport: { width: 960, height: 540 } });
page.setDefaultTimeout(180000);
await page.goto(`http://127.0.0.1:${port}/?seed=EUCLID&nolock=1&buildms=40&vclouds=0&farflora=0`);
await page.waitForFunction('window.NMS && window.NMS.booted', null, { timeout: 90000 });
const shot = async (n, ms = 2500) => { await page.waitForTimeout(ms); await page.screenshot({ path: `screenshots/ship/${n}.png`, timeout: 180000 }); console.log('✓', n); };
await page.evaluate('NMS.teleport(0, 0.35)');
await page.evaluate('NMS.shipPortrait(34)');
await shot('05-portrait', 6000);
await page.evaluate('NMS.lookYaw(40)');
await shot('06-portrait-side');
await page.evaluate('NMS.teleport(3, 1.2); NMS.shipPortrait(34);');
await shot('08-portrait-space', 5000);
console.log('DONE');
await browser.close(); server.close(); process.exit(0);
